### ISSUE TITLE
flaky test

### ISSUE THREAD

**Issue by supercaracal** [redis-rb/redis-cluster-client#413]
```
rake aborted!
ClusterController::MaxRetryExceeded: ClusterController::MaxRetryExceeded
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:439:in `block (2 levels) in wait_for_state'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:438:in `step'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:438:in `block in wait_for_state'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:437:in `each'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:437:in `wait_for_state'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:326:in `wait_meeting'
/home/runner/work/redis-cluster-client/redis-cluster-client/test/cluster_controller.rb:65:in `wait_for_cluster_to_be_ready'
/home/runner/work/redis-cluster-client/redis-cluster-client/Rakefile:54:in `block in <top (required)>'
/home/runner/work/redis-cluster-client/redis-cluster-client/vendor/bundle/ruby/3.0.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/bundle:23:in `<main>'
Tasks: TOP => wait
(See full trace by running task with --trace)
```

**Comment by supercaracal** [comment]
It looks to me that this may be a server side matter.
