### ISSUE TITLE
TypeError: String can't be coerced into Integer

### ISSUE THREAD

**Issue by supercaracal** [redis-rb/redis-cluster-client#59]
frequency: low

```
RedisClient::TestCluster::Pooled#test_inspect:
TypeError: String can't be coerced into Integer
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:224:in `+'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:224:in `sum'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:224:in `send_wait_command'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:198:in `send_command'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:130:in `blocking_call'
    /home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:190:in `wait_for_replication'
    /home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:11:in `setup'
```

```
RedisClient::TestCluster::Pooled#test_inspect:
TypeError: Set can't be coerced into Integer
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:224:in `+'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:224:in `sum'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:224:in `send_wait_command'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:198:in `send_command'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:130:in `blocking_call'
    /home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:190:in `wait_for_replication'
    /home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:16:in `teardown'
```

**Comment by supercaracal** [comment]
```
  1) Error:
RedisClient::TestCluster::Pooled#test_pipelined:
TypeError: String can't be coerced into Integer
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/router.rb:143:in `+'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/router.rb:143:in `sum'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/router.rb:143:in `send_wait_command'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster/router.rb:40:in `send_command'
    /home/runner/work/redis-cluster-client/redis-cluster-client/lib/redis_client/cluster.rb:33:in `blocking_call'
    /home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:190:in `wait_for_replication'
    /home/runner/work/redis-cluster-client/redis-cluster-client/test/redis_client/test_cluster.rb:11:in `setup'
```

**Comment by supercaracal** [comment]
Hmm... There might be a case that the `WAIT` command returns string reply.
